<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="SDK\YapilyCoreSDK.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yapily.BO\Yapily.BO.csproj" />
  </ItemGroup>

</Project>
